health-enabled=true
metrics-enabled=true
# LAN WiFi mode:
# hostname=http://192.168.11.198:8080
# USB debugging mode with `adb reverse tcp:8080 tcp:8080`:
hostname=http://localhost:8080
hostname-strict=false
