CREATE TABLE citizens
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    keycloak_id    UUID                                    NOT NULL,
    username       VARCHAR(255),
    first_name     VARCHAR(255)                            NOT NULL,
    last_name      VARCHAR(255)                            NOT NULL,
    address        VARCHAR(255),
    region         VARCHAR(255),
    birth_place    VARCHAR(255),
    birth_date     date,
    cin            VARCHAR(255)                            NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    phone_number   VARCHAR(255),
    email_verified BOOLEAN                                 NOT NULL,
    is_eligible    BOOLEAN                                 NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    is_deleted     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_citizens PRIMARY KEY (id)
);

ALTER TABLE citizens
    ADD CONSTRAINT uc_citizens_cin UNIQUE (cin);

ALTER TABLE citizens
    ADD CONSTRAINT uc_citizens_keycloak UNIQUE (keycloak_id);

CREATE INDEX idx_citizen_cin ON citizens (cin);

CREATE INDEX idx_citizen_keycloak ON citizens (keycloak_id);