CREATE TABLE elections
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id             UUID                                    NOT NULL,
    title                 VARCHAR(255)                            NOT NULL,
    description           TEXT,
    start_time            TIMESTAMP WITHOUT TIME ZONE,
    end_time              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    phase                 VARCHAR(32)                             NOT NULL,
    contract_address      VARCHAR(42)                             NOT NULL,
    external_nullifier    DECIMAL(78)                             NOT NULL,
    coordinator_id        BIGINT                                  NOT NULL,
    encryption_public_key BYTEA                                   NOT NULL,
    decryption_key        BYTEA,
    CONSTRAINT pk_elections PRIMARY KEY (id)
);

ALTER TABLE elections
    ADD CONSTRAINT uc_elections_contractaddress UNIQUE (contract_address);

ALTER TABLE elections
    ADD CONSTRAINT uc_elections_publicid UNIQUE (public_id);

CREATE UNIQUE INDEX idx_elections_contract_address ON elections (contract_address);

CREATE INDEX idx_elections_end_time ON elections (end_time);

CREATE UNIQUE INDEX idx_elections_public_id ON elections (public_id);

ALTER TABLE elections
    ADD CONSTRAINT FK_ELECTIONS_COORDINATOR FOREIGN KEY (coordinator_id) REFERENCES citizens (id);