package org.krino.voting_system.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "ballots", indexes =
        {
                @Index(name = "idx_ballot_election", columnList = "election_id"),
                @Index(name = "idx_ballot_nullifier", columnList = "nullifier_hash")
        },
        uniqueConstraints =
        {
                @UniqueConstraint(columnNames = {"nullifier_hash"})
        })
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Ballot
{

    @Id
    @Column(columnDefinition = "uuid", updatable = false, nullable = false)
    private UUID id = UUID.randomUUID();

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "election_id", nullable = false)
    private Election election;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "candidate_id", nullable = false)
    private Candidate candidate;


    @Column(name = "nullifier_hash", nullable = false, unique = true, length = 128)
    private String nullifierHash;

    /**
     * The Cryptographic Proof.
     * This is a massive string generated by the frontend (snarkjs/semaphore).
     * It proves: "I am in the Merkle Tree for this Election, and here is my Nullifier."
     * Stored as TEXT because proofs can be large JSON blobs.
     */
    @Column(name = "zk_proof", nullable = false, columnDefinition = "TEXT")
    private String zkProof;

    @Column(name = "transaction_hash", nullable = false)
    private String transactionHash;

    @Column(name = "block_number")
    private Long blockNumber;

    @CreationTimestamp
    @Column(name = "cast_at", updatable = false)
    private LocalDateTime castAt;

    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Ballot ballot = (Ballot) o;
        return id != null && id.equals(ballot.id);
    }

    @Override
    public int hashCode()
    {
        return getClass().hashCode();
    }
}